# SPDX-License-Identifier: Apache-2.0
# Code authors: Vijay and Codex
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule: {interval: weekly}
    groups:
      go-dependencies:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule: {interval: weekly}
    groups:
      actions:
        patterns: ["*"]
